# %W%	(ULTRIX)	%G%
#
# Low level generic makefile
#

all:
	pwd
	@echo $@ is done...

install: all
	pwd
	@echo $@ is done...

sccsinfo:
	pwd
	@echo $@ is done...

sccsget:
	pwd
	@echo $@ is done...

clean:
	pwd
	@echo $@ is done...

clobber:
	pwd
	@echo $@ is done...

depend:
	pwd
	@echo $@ is done...
