.TH linenum 5 RISC
.SH Name
linenum \- line number entries in a MIPS object file
.SH Description
If the
.PN cc
command is invoked with the 
.PN -g
option, an entry is generated
in the object file for each C source line on which a breakpoint can
occur.  You can then reference line numbers when using the 
appropriate software test system.  
.SH See Also
cc(1), dbx(1), a.out(5)
