.\" SCCSID: @(#)rpc.5	8.1	9/11/90
.TH rpc 5 
.SH Name
rpc \- remote procedure call file
.SH Description
.NXR "protocols file" "format"
.NXR "Internet" "specifying protocols"
.NXR "Internet File Transfer Protocol"
.NXA "protocols file" "remote file"
.NXAM "getprotoent subroutine" "protocols file"
The
.PN rpc
file is an ASCII file that contains the following information:
.HP 10
rpc name
.br
.ns
.HP 10
numerical rpc ID
.br
.ns
.HP 10
aliases
.PP
Each 
.PN rpc
name is separated from the next by a new line.
Items are separated by any number of blanks or
tab characters or both.  A number sign (#) indicates the beginning of
a comment; characters up to the end of the line are
not interpreted by routines that search the file.
.PP
The 
.PN rpc
database can be distributed in a network by a naming service, 
such as Yellow Pages or BIND/Hesiod.  See the
.I Guide to the Yellow Pages Service
or the 
.I Guide to the BIND/Hesiod Service
for setup information.
.SH Files
.PN /etc/rpc
.SH See Also
getrpcent(3n)
.br
.I Guide to the BIND/Hesiod Service
.br
.I Guide to the Yellow Pages Service
 
