.\" SCCSID: @(#)dup.4	8.1	9/11/90
.TH dup 4 VAX
.SH Name
dup \- BISYNC data communications interface
.SH Syntax
.B "device dup0 at uba0 csr 0170000 flags 0x0f vector duprint dupxint"
.SH Description
.NXR "dup interface"
.NXR "BISYNC data communications interface"
.NXAM "2780e emulator spooler" "BISYNC communications interface"
The 
.PN dup
data communications
device is used only with the 2780/3780
Terminal
Emulator.  
It has no programmable user interface.  
.PP
When a system
is generated for 2780/3780 emulation on UNIBUS host machines, 
the 
.PN dup 
data communications device must 
be specified in the configuration file as 
.PN dup0 .
.PP
To boot a UNIBUS device having 2780/3780
emulation, the 
.PN dup 
must be specified in the 
.PN rc.local 
file.  
This device is specified by removing the comment sign from the command
line already placed in the 
.PN rc.local
file:
.EX
#/etc/bscconfig dup0 bsc 1
.EE
.PP
The 
.PN dup
data communications device is used with the
DF126 modem.  
.SH Files
.PN /etc/rc.local
.br
.PN /etc/bscconfig
.SH See Also
2780e(1), 3780e(1), 2780d(8)
