.\" SCCSID: @(#)rd.4	8.1	9/11/90
.TH rd 4 VAX
.SH Name
rd \- RD31, RD32, RD53, RD54 Small VAX Winchester disks 
.SH Description
.\"This page exists solely to cross-reference sdc.4
.NXS "rd keyword" "RD31 disk interface"
.NXS "rd keyword" "RD32 disk interface"
.NXS "rd keyword" "RD53 disk interface"
.NXS "rd keyword" "RD54 disk interface"
The 
.PN rd 
Winchester disks, when used either by the workstation
or multiuser configurations of the busless Small VAX processor,
are supported by the SDC disk driver.
The SDC driver handles RD31, RD32, RD53, and RD54 disks on
drives 0 and 1.
.SH Files
.PN /dev/rd[0-1] [a-f]
.br
.PN /dev/rrd[0-1] [a-f]
.SH See Also
sdc(4)
