.\" SCCSID: @(#)chpt.8	8.1	9/11/90
.TH chpt 8 
.SH Name
chpt \- change a disk partition table
.SH Syntax
.B /etc/chpt
[ \fB\-a\fR ]
[ \fB\-d\fR ]
[ \fB\-q\fR ]
[ \fB\-v\fR ]
[ [ \fB\-p\fR\fIx\fR \fIoffset\fR \fIsize\fR ] ... ]
.I device
.SH Description
.NXB "chpt command"
.NXB "disk partition table" "changing"
.NXR "disk partition table" "changing procedure"
The
.PN chpt
command lets you alter the partition sizes
of a disk pack.  Using 
.PN chpt, 
you can tailor your system disks and their
partitions to suit your system's individual needs.
.PP
If you want to create a file system on a partition that has been
modified, you must use 
.MS newfs 8 .
.PP
The standard procedure to change a partition table is:
.IP "1." 0.3i
Look at the current partition table using the \fB\-q\fR
option.
.IP "2." 0.3i
If a file system does not exist on the \fIa\fR partition, create
one using the 
.MS newfs 8 
command.
.IP "" 0.3i
If a file system exists on the \fIa\fR partition but does
not contain a partition table in its superblock, copy the
partition table from the driver to the superblock using
the
.PN chpt
command
with the \fB\-a\fR option.
.IP "3." 0.3i
Change the partition offsets and sizes using the \fB\-p\fIx\fR
option.  You can change all the partitions for one pack on one
command line.
.PP
The device
must be either the \fIa\fR or \fIc\fR partition of the raw
device, depending upon where the file system resides.  For
example, if the file system resides in the \fIa\fR
partition of an RM05 in drive 0, \fIdevice\fR is
rhp0a.
.PP
A file system must exist on the \fIa\fR or \fIc\fR partition
of the pack.  If you do not have a file system there, create one
using 
.MS newfs 8 .
.SH Options
.NXR "chpt command" "options"
.IP \fB\-a\fR 6
Copies the partition table in the device driver
to the disk pack.
.IP \fB\-d\fR 6
Copies the default partition table
to the disk pack and to the current partition table in the driver.
The default partition table is the table that was built with the 
disk driver.
.IP \fB\-q\fR
Runs
.PN chpt
without modifying the partition tables.
This prints the partition table of the specified disk pack. 
It prints the default partition table in the driver if there
is no partition table on the disk pack.
.IP \fB\-v\fR
Prints verbose messages showing
the progress of 
.PN chpt .
.IP \fB\-p\fR\fIx\fR
Changes the parameters of partition \fIx\fR on the disk pack
to the specified \fIoffset\fR and \fIsize\fR.
\fIx\fR is the partition you are modifying (a, b, c, d, e, f, g, or h).
\fIOffset\fR is the new beginning sector,
and \fIsize\fR is the new total number of sectors of the partition
being modified.
.SH Examples
.NXR(e) "disk partition table" "changing"
This example shows how to change the partition table on an RM05
disk pack in drive 1.
The commands in this example change the the size of the \fIh\fR
partition to include the \fIg\fR partition.
Comments are in parenthesis to the right of commands.
.EX 0
.ta 2.5i
% chpt \-q /dev/rhp1a	(\fRview partition table\fP)
/dev/rhp1a
No partition table found in superblock...
using default table from device driver.
Current partition table:
partition       bottom       top      size    overlap
    a                0     15883     15884    c
    b            16416     49855     33440    c
    c                0    500383    500384    a,b,d,e,f,g,h
    d           341696    357579     15884    c,g
    e           358112    414047     55936    c,g
    f           414048    500287     86240    c,g
    g           341696    500287    158592    c,d,e,f
    h            49856    341201    291346    c
%
.EE
.NT
In all of the tables generated by 
.PN chpt ,
\fIbottom\fR is the offset (starting sector),
\fItop\fR is the ending sector,
and \fIsize\fR is the number of sectors in the partition.
The \fIoverlap\fR is the other sectors that are partially
or entirely included in the partition.
.NE
.EX 0
.ta 2i
% bc	(\fRbasic calculator\fP)
500287-49856	(\fRtop of \fIg\fR minus bottom of \fIh\fR\f(CW)
450431
450431+1	(\fRadd 1 because it is zero\-based\fP)
450432	(\fRsize of new \fIh\fR partition\f(CW)
%
.EE
.PP
From the query,
you can see that there is no partition table in the superblock
of the \fIa\fR partition.
If this is because there is no file system in the \fIa\fR
partition,
run the 
.PN newfs
command to create one.
.PP
For this example,
assume that there is a file system in the \fIa\fR partition of the disk,
but the file system does not contain a partition table in its
superblock.
Therefore, run 
.PN chpt
with the \fB\-a\fR option to copy the partition table
in the driver to the superblock of the \fIa\fR partition.
.EX 0
.ta 2.5i
% chpt \-a /dev/rhp1a	(\fRadd table to \fIa\fR partition\f(CW)
%
.EE
.PP
Now you have a partition table to change.
.EX 0
.ta 4i
% chpt \-v \-ph 49856 450432 /dev/rhp1a	(\fRchange \fIh\fR\f(CW)
/dev/rhp1a
New partition table:
partition       bottom  top     size    overlap
    a                0   15883   15884  c
    b            16416   49855   33440  c
    c                0  500383  500384  a,b,d,e,f,g,h
    d           341696  357579   15884  c,g,h
    e           358112  414047   55936  c,g,h
    f           414048  500287   86240  c,g,h
    g           341696  500287  158592  c,d,e,f,h
    h            49856  500287  450432  c,d,e,f,g
%
.EE
.PP
.SH Caution
.NXR(c) "disk partition table" "changing indiscriminately"
Changing partition tables indiscriminately
can result in losing large amounts of data.
.PP
Check for file systems on all the partitions of the disk
before using the \fB\-p\fR option.
If a file system exists whose partition may be destroyed,
copy it to a backup medium.
After you have changed the partitions,
restore the backed up file system.
.SH Restrictions
.NXR "chpt command" "restricted"
You must have superuser privileges to use
.PN chpt .
.PP 
You can not shrink or change the offset of a partition
with a file system mounted on it
or with an open file descriptor on the entire partition.
.PP
You can not change the offset of the \fIa\fR partition.
.SH See Also
ioctl(2), disktab(5), fsck(8), mkfs(8), newfs(8)
.br
.I "Guide to System Disk Maintenance"
.NXE "chpt command"
.NXE "disk partition table" "changing"
