!
! HP BOOT COMMAND FILE - MASSBUS DISK
!
! THE MASSBUS TR LEVEL MUST BE DEPOSITED IN R1 AND THE
! UNIT NUMBER MUST BE DEPOSITED IN R3 BEFORE EXECUTING THIS PROCEDURE
!
HALT			! HALT PROCESSOR
UNJAM			! UNJAM SBI
INIT			! INIT PROCESSOR
DEPOSIT/I 11 20003800	! SET UP SCBB
DEPOSIT R0 0		! DISK PACK DEVICE TYPE
!R1 MUST BE PRESET TO THE DESIRED MBA TR LEVEL
DEPOSIT R2 0		! ADAPTER UNIT = 0
!R3 MUST BE PRESET TO THE DESIRED UNIT NUMBER
DEPOSIT R4 0		! BOOT BLOCK LBN (UNUSED)
DEPOSIT R5 1000B	! SOFTWARE BOOT FLAGS
DEPOSIT FP 0		! SET NO MACHINE CHECK EXPECTED
START 20003000		! START ROM PROGRAM
WAIT DONE		! WAIT FOR COMPLETION
			! 
EXAMINE SP		! SHOW ADDRESS OF WORKING MEMORY+^X200
LOAD VMB.EXE/START:@	! LOAD PRIMARY BOOTSTRAP
START @			! AND START IT
