/*  sccsid  =  @(#)ulliterals.h	4.1   (ULTRIX)   7/2/90  */

/*
*	.TITLE	ULLITERALS - Literal definitions for ERIT
*	.IDENT	/1-001/
*
* COPYRIGHT (C) 1985 DIGITAL EQUIPMENT CORP.,
* CSSE SOFTWARE ENGINEERING
* MARLBOROUGH, MASSACHUSETTS
*
* THIS SOFTWARE IS FURNISHED UNDER A LICENSE FOR USE ONLY ON A 
* SINGLE COMPUTER SYSTEM AND MAY BE COPIED ONLY WITH THE INCLUSION
* OF THE ABOVE COPYRIGHT NOTICE.  THIS SOFTWARE,  OR ANY OTHER
* COPIES THEREOF, MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE
* TO ANY OTHER PERSON EXCEPT FOR USE ON SUCH SYSTEM AND TO ONE WHO
* AGREES TO THESE LICENSE TERMS.  TITLE TO AND OWNERSHIP OF THE
* SOFTWARE SHALL AT ALL TIMES REMAIN IN DEC.
*
* THE INFORMATION IN THIS SOFTWARE IS SUBJECT TO CHANGE WITHOUT
* NOTICE AND SHOULD NOT BE CONSTRUED AS A COMMITMENT BY DIGITAL
* EQUIPMENT CORPORATION.
*
* DEC ASSUMES NO RESPONSIBILITY FOR THE USE OR RELIABILITY OF
* ITS SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DEC.
*
*++
*
* FACILITY:		[ FMA Software Tools - Detail Design ]
*
* ABSTRACT:
*
*	This header file contains the literals used by ULFILE for error
*	checking and return values to its callers
*	
*	
* ENVIRONMENT:	ULTRIX-32 C
*	
* AUTHOR:  Bob Winant,  CREATION DATE:  28-Jan-86
*
* MODIFIED BY:
*
*--
*/

#define UL$BUFFSIZE 2056	/* buffer size for read */
#define UL$RCL  2		/* byte length of data for reading */
#define UL$TRSIZ 4		/* Length of trailer identifier */
#define UL$BYT 1		/* Single byte size */
