.TH packetfilter 4
.SH Name
packetfilter \- Ethernet packet filter
.SH Syntax
.B "options	PACKETFILTER"
.br
.B "pseudo-device	packetfilter"
.SH Description
.NXR "packetfilter"
The packet filter pseudo-device driver
provides a raw interface to Ethernets and similar network data link layers.
Packets received that are not used by the kernel
(for example, to support the IP and DECnet protocol families)
are available through this mechanism.
The packet filter driver is kernel-resident code provided by
the ULTRIX operating system.  The driver appears to
applications as a set of character special files, one
for each open packet filter application.
(Throughout this reference page, the word
.I file
refers to such a character special file.)
.PP
You create the minor device files
with the
.MS MAKEDEV 8
script using
these commands:
.EX
# \f(CBcd /dev\fP
# \f(CBMAKEDEV pfilt
.EE
A single call to
.PN MAKEDEV
with an argument of
.PN pfilt
creates 64 character special files in 
.PN /dev/pf ,
which are named
.PN pfilt\fInnn ,
\fRwhere \fInnn\fP is
the unit number.
Successive calls to
.PN MAKEDEV
with arguments of
.PN pfilt1 ,
.PN pfilt2 ,
and
.PN pfilt3
make additional sets of 64 sequentially numbered packet filters
to a maximum of 256.
The maximum number of packet filter special files
is limited to 256, which is the maximum number of
minor device numbers allowed for each major device number.
(See 
.MS MAKEDEV 8 
for more information on making system special files.)
.PP
For opening these special files, the ULTRIX operating system
provides the
.MS pfopen 3 
library routine.
.PP
Associated with each open instance of a
packet filter special
file is a user-settable packet filter ``program''
that is used to select which incoming 
packets are delivered by that
packet filter special file.
Whenever a packet is received from the net,
the packet filter driver successively applies the filter
programs of each of the open packet filter files to the
packet, until one filter program ``accepts'' the packet.
When a filter accepts the packet,
it is placed on the packet input queue of the
associated special file.
If no filters accept the packet, it is discarded.
The format of a packet filter is described later.
.PP
Reads from these files return the next packet
from a queue of packets that have matched the filter.
If the read operation specifies insufficient buffer space
to store the entire packet,
the packet is truncated and the trailing contents lost.
Writes to these files transmit packets on the
network, with each write operation generating exactly one packet.
.PP
The packet filter supports a variety of different Ethernet
data-link levels:
.IP "10Mb Ethernet"
.br
Packets consist of fourteen or more bytes, with the first six
bytes specifying the destination Ethernet address,
the next six bytes the source Ethernet address,
and the next two bytes specifying the packet type.
(This is the Standard Ethernet.)
.IP "3Mb Ethernet"
.br
Packets consist of four or more bytes, with the first byte
specifying the source Ethernet address, the second
byte specifying the destination Ethernet address,
and the next two bytes specifying the packet type.
(On the network, the source and destination addresses
are in the opposite order.)
.br
.ne 6
.IP "Byte-swapping 3Mb Ethernet"
.br
Packets consist of four or more bytes, with the first byte
specifying the source Ethernet address, the second
byte specifying the destination Ethernet address,
and the next two bytes specifying the packet type.
Each short word (pair of bytes) is swapped from the network
byte order.  This device type is provided only for
backwards-compatibility.
.PP
The remaining words are interpreted according to the packet type.
Note that 16-bit and 32-bit quantities may have to be byteswapped
(and possibly short-swapped) to be intelligible on an ULTRIX system.
.PP
The packet filters treat the entire packet,
including headers, as uninterpreted data.
The user must supply
the headers for transmitted packets (although the system makes sure that
the source address is correct) and the headers of received packets
are delivered to the user.
The packet filter mechanism does not know anything about the data
portion of the packets it sends and receives.
.PP
In addition to the FIONREAD
.PN ioctl
request (described in the 
.MS tty 4
reference page), the application can apply several special
.PN ioctl
requests to an open
packet filter file.  The calls are divided into five categories:
packet-filter specifying,
packet handling,
device configuration,
administrative,
and miscellaneous.
.br
.ne 1i
.SS Packet-filter Specification ioctl Request
The
.PN EIOCSETF
.PN ioctl
is central to the operation of the packet filter interface, because
it specifies which packets the application wishes to receive.
It is used to set the packet filter ``program''
for an open
packet filter file, and is of the form:
.EX
ioctl(\fIfildes\fP, EIOCSETF, \fIfilter\fP)
struct enfilter *\fIfilter\fP
.EE
The
.PN enfilter
structure is defined in 
.PN <net/pfilt.h>
as:
.EX
.ta \w'struct 'u \w'struct u_short  'u
struct enfilter
{
	u_char	enf_Priority;
	u_char	enf_FilterLen;
	u_short	enf_Filter[ENMAXFILTERS];
};
.DT
.EE
.PP
A packet filter consists of a priority,
the filter command list length (in shortwords),
and the filter command list itself.
Each filter command list specifies
a sequence of actions that
operate on an internal stack.
Each shortword of the
command list specifies an action and a binary operator.  
.SS Command List Actions
The action
can be one of the following:
.IP ENF_PUSHLIT
.br
Pushes the next shortword of the command list on the stack.
.IP ENF_PUSHWORD+N
.br
Pushes shortword N of the incoming packet on the stack.
.br
.ne 3
.IP ENF_PUSHZERO
.br
Pushes a zero.  Is slightly faster than ENF_PUSHLIT with an
explicit literal.
.IP ENF_PUSHONE
.br
Pushes a one.  Is slightly faster than ENF_PUSHLIT with an 
explicit literal.
.IP ENF_PUSHFFFF
.br
Pushes 0xFFFF.  Is slightly faster than ENF_PUSHLIT with an
explicit literal.
.IP ENF_PUSH00FF
.br
Pushes  0x00FF.  Is slightly faster than ENF_PUSHLIT with an
explicit literal.
.IP ENF_PUSHFF00
.br
Pushes 0xFF00.  Is slightly faster than ENF_PUSHLIT with an
explicit literal.
.IP ENF_NOPUSH
.br
Defined as zero.
.SS Binary Operators
When both an action and an operator are specified in the
same shortword, the action is performed, followed by the
operation.
You can combine an action with an operator 
using bitwise OR;
for example,
.EX
((ENF_PUSHWORD+3) | ENF_EQ)
.EE
.PP
The binary operator, which can be one of the following, operates on
the top two elements of the stack and replaces them with its
result:
.IP ENF_EQ 15
Returns true if the result is equal.
.IP ENF_NEQ
Returns true if the result is not equal.
.IP ENF_LT
Returns true if the result is less than.
.IP ENF_LE
Returns true if the result is less than or equal.
.IP ENF_GT
Returns true if the result is greater than.
.IP ENF_GE
Returns true if the result is greater than or equal.
.IP ENF_AND
Returns the result of the binary AND operation.
.IP ENF_OR
Returns the result of the binary OR operation.
.IP ENF_XOR
Returns the result of the binary XOR operation.
.IP ENF_NOP
Defined as zero.
.IP ENF_CAND
Returns false immediately if the result is false,
and continues execution of the filter otherwise.
(Short-circuit operator)
.IP ENF_COR
Returns true immediately if the result is true,
and continues execution of the filter otherwise.
(Short-circuit operator)
.IP ENF_CNAND
Returns true immediately if the result is false,
and continues execution of the filter otherwise.
(Short-circuit operator)
.IP ENF_CNOR
Returns false immediately if the result is true,
and continues execution of the filter otherwise.
(Short-circuit operator)
.PP
The short-circuit operators are so called because they terminate
the execution of the filter immediately if the condition they are 
checking for is found, and continue otherwise.
All the short-circuit operators pop two elements from the stack and 
compare them for equality.
Unlike the other binary operators, these four operators do not leave a result
on the stack, even if they continue.
.PP
Use the short-circuit operators whenever possible, to reduce the
amount of time spent evaluating filters.  When you use them, you should
also arrange the order of the tests so that the filter will succeed or fail
as soon as possible. For example, checking a word in
an address field of an Ethernet packet 
is more likely to indicate failure than the Ethernet type field.
.PP
The
special action
ENF_NOPUSH
and the special operator
ENF_NOP
can be used to only perform the binary operation or
to only push a value on the stack.
Because both are defined to be zero, specifying
only an action actually specifies the action followed by
ENF_NOP, and specifying only an operation actually specifies
ENF_NOPUSH
followed
by the operation.
.PP
After executing the filter command list, a nonzero value (true)
left on top of the stack
(or an empty stack) causes the incoming
packet to be accepted for the corresponding
packet filter file and a zero value (false) causes the packet to
be passed through the next packet filter.
If the filter exits as the result of a short-circuit operator,
the top-of-stack value is ignored.
Specifying an undefined operation or action in the command list
or performing an illegal operation or action (such as pushing
a shortword offset
past the end of the packet or executing a binary operator
with fewer than two shortwords on the stack) causes a filter to
reject the packet.
.PP
To resolve problems with
overlapping or conflicting packet filters,
the filters for each open
packet filter file are ordered by the driver
according to their priority
(lowest
priority is 0, highest is 255).
When processing incoming
packets, filters are applied according to their
priority (from highest to lowest) and
for identical priority values according to their
relative ``busyness'' (the filter that has previously
matched the most packets is checked first), until one or more filters
accept the packet or all filters reject it and
it is discarded.
.PP
Normally once a packet is delivered to a filter, it is not presented to any
other filters.  However, if the packet is accepted by a filter in
nonexclusive mode (ENNONEXCL set using EIOCMBIS,
described in the following section), the packet is
passed along to lower-priority filters and may be delivered more than
once.
The use of nonexclusive filters imposes an additional cost on
the system, because it increases the average number of filters applied to each
packet.
.PP
The packet filter for a packet filter file is initialized
with length 0 at priority 0 by
.MS open 2 ,
and hence, by default, accepts all
packets in which no higher-priority filter
is interested.
.PP
Priorities should be assigned so that, in general, the more packets a
filter is expected to match, the higher its priority.  This prevents
a lot of checking of packets against filters that are unlikely
to match them.
.br
.ne 3i
.PP
The filter in this example accepts incoming
RARP (Reverse Address Resolution Protocol) broadcast packets.
.PP
The filter first checks the Ethernet type of the packet.
If it is not a RARP (Reverse ARP) packet, it is discarded. 
Then, the RARP type field is checked for a reverse request (type 3),
followed by a check for a broadcast destination address.
Note that the packet type field is checked before the destination address,
because the total number of broadcast packets on the network is larger
than the number of RARP packets.  Thus, the filter is
ordered with a minimum amount of processing overhead.
.EX
.ta \w'stru'u \w'struct ENF_PUSHWORD,      'u
struct enfilter f =
{
	36, 0,	/* priority and length */
	ENF_PUSHWORD + 6,
	ENF_PUSHLIT, 0x3580,
	ENF_CAND,	/* Ethernet type == 0x8035 (RARP) */
	ENF_PUSHWORD + 10,
	ENF_PUSHLIT, 0x0300,
	ENF_CAND,	/* reverse request type = 0003 */
	ENF_PUSHWORD + 0,
	ENF_PUSHLIT, 0xFFFF,
	ENF_CAND,	/* dest addr = FF-FF */
	ENF_PUSHWORD + 1,
	ENF_PUSHLIT, 0xFFFF,
	ENF_CAND,	/* dest addr = FF-FF */
	ENF_PUSHWORD + 2,
	ENF_PUSHLIT, 0xFFFF,
	ENF_EQ	/* dest addr = FF-FF */
};
.DT
.EE
.PP
Note that shortwords, such as the packet type field, are in network
byte-order.
The literals you compare them to may have to be byte-swapped
on machines like the VAX.
.br
.ne 3i
.PP
By taking advantage of the ability to
specify both an action and operation in each word of
the command list, you could abbreviate the filter to the
following:
.EX
.ta \w'stru'u \w'struct ENF_PUSHLIT | ENF_CAND,  'u
struct enfilter f =
{
	36, 0,	/* priority and length */
	ENF_PUSHWORD + 6,
	ENF_PUSHLIT | ENF_CAND,
	0x3580,	/* Ethernet type == 0x8035 (RARP) */
	ENF_PUSHWORD + 10,
	ENF_PUSHLIT | ENF_CAND,
	0x0300,	/* reverse request type = 0003 */
	ENF_PUSHWORD + 0,
	ENF_PUSHFFFF | ENF_CAND,	/* dest addr = FF-FF */
	ENF_PUSHWORD + 1,
	ENF_PUSHFFFF | ENF_CAND,	/* dest addr = FF-FF */
	ENF_PUSHWORD + 2,
	ENF_PUSHFFFF | ENF_EQ	/* dest addr = FF-FF */
};
.DT
.EE
.ne 1i
.SS Packet-Handling ioctl Requests
These
.PN ioctl
requests control how the packet filter processes input packets
and returns them to the application process.
The most useful of these requests set and clear so-called
``mode bits'' for the file and are of this form:
.EX
ioctl(\fIfildes\fP, \fIcode\fP, \fIbits\fP)
u_short *\fIbits\fP;
.DT
.EE
.i0
.PP
In these calls,
.I bits
is a bitmask specifying which bits to set or clear.  The applicable
.I codes
are:
.IP EIOCMBIS
.br
Sets the specified mode bits.
.IP EIOCMBIC
.br
Clears the specified mode bits.
.br
.ne 1i
.PP
The bits 
are:
.IP ENTSTAMP
.br
If set, a received packet is preceded by a header structure (see the
description of
.PN enstamp
following) that includes a time stamp and other information.
.IP ENBATCH
.br
If clear, each
.MS read 2
system call returns at most one packet.  If set, a
.PN read
call might return more than one packet, each of which is preceded by an
.PN enstamp
header.
.IP ENPROMISC
.br
If set, this filter will be applied to promiscuously-received packets.
This puts the interface into ``promiscuous mode'' only if this
has been allowed by the superuser using the EIOCALLOWPROMISC
.PN ioctl
call (described later).
.IP ENCOPYALL
.br
If set, this filter will see packets sent and received by the
kernel-resident protocols of the local host.  (Normally, these packets
are not copied to the packet filter.)  This mode takes effect only if this
has been allowed by the superuser using the EIOCALLOWCOPYALL
.PN ioctl
call (described later).
.br
.ne 4
.IP ENNONEXCL
.br
If set, packets accepted by this filter will be available to
any lower-priority filters.  If clear, no lower-priority filter will see
packets accepted by this filter.
.IP ENHOLDSIG
.br
If clear,
means that the driver should
disable the effect of EIOCENBS (described later)
once it has delivered a signal.
If set (the default), the effect of EIOCENBS persists.
.PP
The
.PN enstamp
structure contains useful information about the packet that immediately
follows it; in ENBATCH mode, it also allows the reader to separate the
packets in a batch.  It is defined in
.PN <net/pfilt.h>
as:
.EX
.ta \w'struct 'u +\w'struct timeval  'u
struct enstamp {
	u_short	ens_stamplen;
	u_short	ens_flags;
	u_short	ens_count;
	u_short	ens_dropped;
	u_long	ens_ifoverflows;
	struct	timeval	ens_tstamp;
};
.EE
.i0
.DT
.PP
The fields are:
.IP ens_stamplen
.br
The length of 
.PN enstamp
structure in bytes.  The packet data follows immediately.
.br
.ne 1.25i
.IP ens_flags
.br
Indicates how the packet was received. The bits 
are:
.RS
.IP ENSF_PROMISC
.br
Received promiscuously (unicast to some other host).
.IP ENSF_BROADCAST
.br
Received as a broadcast.
.IP ENSF_MULTICAST
.br
Received as a multicast.
.IP ENSF_TRAILER
.br
Received in a trailer encapsulation.  The packet has been rearranged into
header format.
.RE
.br
.ne .5i
.IP ens_count
.br
The length of the packet in bytes (does not include the
.PN enstamp
header).
.br
.ne .5i
.IP ens_dropped
.br
The number of packets accepted by this filter but dropped because the input
queue was full; this is a cumulative count since the previous
.PN enstamp
was read from this
packet filter
file.  This count may be completely wrong if the ENNONEXCL mode
bit is set for this filter.
.br
.ne .5i
.IP ens_ifoverflows
.br
The total number of input overflows reported by the network interface since the
system was booted.
.br
.ne .5i
.IP ens_tstamp
.br
The approximate time the packet was received.
.br
.PP
If the buffer returned by a batched
.MS read 2
contains more than one packet, the offset from the beginning of the buffer
at which each
.PN enstamp
structure begins is an integer multiple of the word-size of the processor.
For example, on a VAX, each
.PN enstamp
is aligned on a longword boundary (provided that the buffer address passed to
the
.MS read 2
system call is aligned).
The alignment (in units of bytes) is given by the constant
.PN ENALIGNMENT ,
defined in
.PN <net/pfilt.h> .
If you have an integer
.IR x ,
you can use the macro
\f(CWENALIGN(\fIx\fP)\fR
to get the least integer that is a multiple of
.PN ENALIGNMENT
and not less than
\fIx\fR.
For example, this code fragment reads and processes one batch:
.ne 1i
.EX
char *buffer = &(BigBuffer[0]);
int buflen;
int pktlen, stamplen;
struct enstamp *stamp;

buflen = read(f, buffer, sizeof(BigBuffer));
while (buflen > 0) {
    stamp = (struct enstamp *)buffer;
    pktlen = stamp->ens_count;
    stamplen = stamp->ens_stamplen;
    ProcessPacket(&(buffer[stamplen]), pktlen);   /* your code here */
    if (buflen == (pktlen + stamplen))
        break;                             /* last packet in batch */
    pktlen = ENALIGN(pktlen);     /* account for alignment padding */
    buflen -= (pktlen + stamplen);
    buffer += (pktlen + stamplen);          /* move to next stamp */
}
.EE
.PP
If a buffer filled by a batched read
contains more than one packet, the final packet is never truncated.
If, however, the entire buffer is not big enough to contain a single
packet, the packet will be truncated; this is also true for unbatched
reads.  Therefore, the buffer passed to the
.MS read 2
system call should always be big enough to hold the largest
possible packet plus an
.PN enstamp
structure.
(See the 
.PN EIOCDEVP
.PN ioctl
request later in this reference page for 
information on how to determine the maximum packet
size.  See also the
.PN EIOCTRUNCATE
.PN ioctl
request for an example that delivers only the desired
number of bytes of a packet.)
.ne 1.5i
.PP
Normally, a packet filter application blocks in the
.PN read
system call until a received packet is available for reading.
There are several ways to avoid blocking indefinitely: an application
can use the
.MS select 2
system call, it can set a ``timeout'' for the packet filter file,
or it can request the delivery of a signal (see
.MS sigvec 2 )
when a packet matches the filter.
.ne 1i
.i0
.DT
.PP
.IP EIOCSETW
.br
The packet filter interface limits the number of packets that can
be queued for delivery for a specific packet filter file.  Application
programs can vary this ``backlog'', if necessary, using the
following call:
.EX
ioctl(\fIfildes\fP, EIOCSETW, \fImaxwaitingp\fP)
u_int *\fImaxwaitingp\fP;
.EE
The argument
.I maxwaitingp
points to an integer containing
the input queue size to be set.
If this is greater than the maximum allowable
size (see EIOCMAXBACKLOG later), it is set to the maximum.
If it is zero, it is set to a default value.
.br
.ne 1i
.IP EIOCFLUSH
.br
After changing the packet filter program, the input queue may contain packets
that were accepted under the old filter.
To flush the queue of incoming packets, use the following:
.EX
ioctl(\fIfildes\fP, EIOCFLUSH, 0)
.EE
.ne 1i
.IP EIOCTRUNCATE
.br
An application, such as a network load monitor, that does not want to
see the entire packet can ask the packet filter to truncate
received packets at a specified length. This action may improve performance
by reducing data movement.  
.sp .5
To specify truncation, use:
.EX
ioctl(\fIfildes\fP, EIOCTRUNCATE, \fItruncationp\fP)
u_int *\fItruncationp\fP;
.EE
The argument
.I truncationp
points to an integer specifying the truncation length, in bytes.
Packets shorter than this length are passed intact.
.PP
This example, a revision of the previous example, illustrates
the use of EIOCTRUNCATE, which causes the packet filter to
deliver only the first \fIn\fR bytes of a packet, not the
entire packet.
.ne 1i
.EX
char *buffer = &(BigBuffer[0]);
int buflen;
int pktlen, stamplen;
struct enstamp *stamp;
int truncation = SIZE_OF_INTERESTING_PART_OF_PACKET;

if (ioctl(f, EIOCTRUNCATE, &truncation) < 0)
    exit(1);
    
while (1) {
    buflen = read(f, buffer, sizeof(BigBuffer));
    while (buflen > 0) {
       stamp = (struct enstamp *)buffer;
       pktlen = stamp->ens_count;     /* ens_count is untruncated length */
       stamplen = stamp->ens_stamplen; 
.sp .5
       ProcessPacket(&(buffer[stamplen]), pktlen);     /* your code here */
.sp .5
       if (pktlen > truncation)       /* truncated portion not in buffer */
           pktlen = truncation;
       if (buflen == (pktlen + stamplen))
           break;                                /* last packet in batch */
       pktlen = ENALIGN(pktlen);        /* account for alignment padding */
       buflen -= (pktlen + stamplen);
       buffer += (pktlen + stamplen);              /* move to next stamp */
   }
}

.EE
.PP
Two calls control the timeout mechanism; they are of the following
form:
.EX
#include <net/time.h>
.sp .5
ioctl(\fIfildes\fP, \fIcode\fP, \fItvp\fP)
.sp .5
struct timeval *\fItvp\fP;
.EE
.DT
.i0
.PP
The
.I tvp
argument is the address of a
.PN struct
.PN timeval
containing the timeout interval (this is a relative
value, not an absolute time).  The codes are:
.IP EIOCGRTIMEOUT
.br
Returns the current timeout value.
.br
.ne 4
.IP EIOCSRTIMEOUT
.br
Sets the timeout value.
When the value is
positive, a
.MS read 2
call returns a 0 if no packet arrives during the period.
When the timeout value is zero, reads block indefinitely (this
is the default).  When the value is negative, a
.MS read 2
call returns a 0 immediately if there are no queued packets.
Note that the largest legal timeout value
is a few million seconds.
.PP
Two calls control the signal-on-reception mechanism;
they are of the following form:
.EX
ioctl(\fIfildes\fP, \fIcode\fP, \fIsignp\fP)
u_int *\fIsignp\fP;
.EE
.PP
The argument
.I signp
is a pointer to an integer containing the number
of the signal
to be sent when an input packet arrives.
The applicable
.I codes
are:
.br
.ne 6
.IP EIOCENBS
.br
Enables the specified signal when an input packet
is received for this file.
If the ENHOLDSIG flag (see EIOCMBIS later) is not set,
further signals are automatically disabled
whenever a signal is sent to prevent nesting, and hence
must be explicitly re-enabled after processing.
When the signal number is 0,
this call is equivalent to EIOCINHS.
.IP EIOCINHS
.br
Disables signaling on packet reception.
The
.I signp
argument
is ignored.
This is the default when the file is first opened.
.ne 1i
.SS Device Configuration ioctl Requests
.IP EIOCIFNAME
.br
Each packet filter file is associated with a specific network interface.
To find out the name of the interface underlying the
packet filter file, use the following:
.EX
#include <net/socket.h>
#include <net/if.h>
.sp
ioctl(\fIfildes\fP, EIOCIFNAME, \fIifr\fP)
struct ifreq *\fIifr\fP;
.EE
The interface name (for example, ``de0'') is returned in
.I ifr->ifr_name\fR;
other fields of the
.I struct ifreq
are not set.
.IP EIOCSETIF
.br
To set the interface associated with a packet filter file, use
the following:
.EX
ioctl(\fIfildes\fP, EIOCSETIF, \fIifr\fP)
struct ifreq *\fIifr\fP;
.EE
.sp .5
The interface name should be passed
.I ifr->ifr_name\fR;
other fields of the
.I struct ifreq
are ignored.
The name provided may be one of the actual interface names,
such as ``de0'' or ``qe1'', or it may be a pseudo-interface
name of the form ``pf\fIn\fP'',
used to specify the 
.I n\fRth
\fRinterface attached to the system.
For example, ``pf0'' specifies
the first interface.
This is useful for applications
that do not know the names of specific interfaces.
Pseudo-interface names are never returned by EIOCIFNAME.
.ne 6
.IP EIOCDEVP
.br
To get device parameters of the network interface underlying the
packet filter file, use the following:
.EX
ioctl(\fIfildes\fP, EIOCDEVP, \fIparam\fP)
struct endevp *\fIparam\fP;
.EE
.ne 1.75i
The
.PN endevp
structure is defined in
.PN <net/pfilt.h>
as:
.EX
.ta \w'struct 'u +\w'u_short  'u
struct endevp {
	u_char	end_dev_type;
	u_char	end_addr_len;
	u_short	end_hdr_len;
	u_short	end_MTU;
	u_char	end_addr[EN_MAX_ADDR_LEN];
	u_char	end_broadaddr[EN_MAX_ADDR_LEN];
};
.DT
.EE
The fields are:
.RS
.IP end_dev_type 1.5i
Specifies the device type: ENDT_3MB, ENDT_BS3MB, or ENDT_10MB.
.IP end_addr_len 1.5i
Specifies the address length in bytes (for example, 1 or 6).
.IP end_hdr_len 1.5i
Specifies the total header length in bytes (for example, 4 or 14).
.IP end_MTU 1.5i
Specifies the maximum packet size, including header, in bytes.
.IP end_addr 1.5i
The address of this interface; aligned so that the low order
byte of the address is in
.IR end_addr[0] .
.IP end_broadaddr 1.5i
The hardware destination address for broadcasts on this network.
.RE
.SS Administrative ioctl Requests
.IP EIOCMAXBACKLOG
.br
The maximum queue length that can be set using EIOCSETW depends
on whether the process is running as the superuser or not.  If
so, the maximum is a kernel constant; otherwise, the maximum is a
value that can be set, by the superuser, for each interface.
To set the maximum non-superuser backlog for an interface, use
EIOCSETIF to bind to the interface, and then use the following:
.EX
ioctl(\fIfildes\fP, EIOCMAXBACKLOG, \fImaxbacklogp\fP)
int *\fImaxbacklogp\fP;
.EE
The argument
.I maxbacklogp
points to an integer containing the maximum value.
(If
.I maxbacklogp
points to an integer containing a negative value, it is replaced
with the current backlog value, and no action is taken.)
.IP EIOCALLOWPROMISC
.br
Certain kinds of network-monitoring applications need to place the
interface in ``promiscuous mode'', where it receives all packets on
the network.  Promiscuous mode can be set 
by the superuser with the
.I /etc/ifconfig
command, or the superuser can configure an interface
to go into promiscuous mode automatically if any packet filter applications
have the ENPROMISC mode bit set.  To do so, use
EIOCSETIF to bind to the interface, and then use the following:
.EX
ioctl(\fIfildes\fP, EIOCALLOWPROMISC, \fIallowp\fP)
int *\fIallowp\fP;
.EE
The argument
.I allowp
points to an integer containing a Boolean value (nonzero
means promiscuous mode is set automatically).
(If
.I allowp
points to an integer containing a negative value, it is replaced
with the current Boolean value, and no action is taken.)
.IP EIOCALLOWCOPYALL
.br
Certain promiscuous-mode network-monitoring applications need to see
unicast packets sent or received by the local host.  For reasons of
efficiency, these packets are not normally provided to the packet filter,
but in ``copy all'' mode they are.  The superuser can configure an 
interface to go into copy-all mode automatically if any packet filter
applications have the ENCOPYALL mode bit set.  To do so, use EIOCSETIF
to bind to the interface, and then use the following:
.EX
ioctl(\fIfildes\fP, EIOCALLOWCOPYALL, \fIallowp\fP)
int *\fIallowp\fP;
.EE
The argument
.I allowp
points to an integer containing a Boolean value (nonzero
means copy-all mode is set automatically).
(If
.I allowp
points to an integer containing a negative value, it is replaced with
the current Boolean value, and no action is taken.)
.IP EIOCMFREE
.br
To find out how many packet filter files remain for opening, use this
.PN ioctl ,
which places the number in the integer pointed to by
\fImfree\fR:
.EX
ioctl(\fIfildes\fP, EIOCMFREE, \fImfree\fP)
int *\fImfree\fP;
.EE
.br
.ne 1.5i
.SS Miscellaneous ioctl Requests
Two calls are provided for backwards compatibility and should not be used
in new code.  These calls are used to set and fetch parameters
of a packet filter file
(\fInot\fR
the underlying device; see EIOCDEVP).
The form for these calls is:
.EX
#include <sys/types.h>
#include <net/pfilt.h>
.sp .5
ioctl(\fIfildes\fP, \fIcode\fP, \fIparam\fP)
.sp .5
struct eniocb *\fIparam\fP;
.EE
.sp .5
The structure
.PN eniocb
is defined in 
.PN <net/pfilt.h>
as:
.EX
.ta \w'struct 'u +\w'u_char  'u
struct eniocb
{
	u_char	en_addr;
	u_char	en_maxfilters;
	u_char	en_maxwaiting;
	u_char	en_maxpriority;
	long	en_rtout;
};
.DT
.EE
.i0
.sp .5
The applicable
.I codes
are:
.IP EIOCGETP
.br
Fetch the parameters for this file.
.IP EIOCSETP
.br
Set the parameters for this file.
.i0
.DT
.sp .5
All the fields, which are described later, except \fIen_rtout\fR,
are read-only.
.RS
.IP en_addr 1.5i
No longer maintained; use EIOCDEVP.
.IP en_maxfilters 1.5i
The maximum length of a filter command list; see EIOCSETF.
.br
.ne 3
.IP en_maxwaiting 1.5i
The maximum number of packets that can be queued for reading on the
packet filter
file; use EIOCMAXBACKLOG.
.IP en_maxpriority 1.5i
The highest allowable filter priority; see EIOCSETF.
.IP en_rtout 1.5i
The number of clock ticks to
wait before timing out on a read request and returning a zero length.
If zero, reads block indefinitely until a packet arrives.
If negative, read requests return a zero length
immediately if there are no packets in the input queue.
Initialized to zero by
.MS open 2 ,
indicating no timeout.
(Use EIOCSRTIMEOUT and EIOCGRTIMEOUT.)
.RE
.br
.ne 1.5i
.SH Restrictions
Because the packet filter include file 
.PN <net/pfilt.h>
was originally named 
.PN <sys/enet.h> ,
some filter applications may need to be updated.
.PP
A previous restriction against accessing data words past approximately
the first
hundred bytes in a packet has been removed.  However, it becomes
slightly more costly to examine words that are not near the beginning
of the packet.
.PP
Because packets are streams of bytes, yet the filters operate
on short words, and standard network byte order is usually opposite
from VAX byte order, the relational operators
ENF_LT, ENF_LE,
ENF_GT,
and
ENF_GE
are not particularly useful.  If this becomes a severe problem,
a byte-swapping operator could be added.
.SH Files
.PN /dev/pf/pfilt\fInnn
\fR	Packet filter special files
.SH See Also
ethers(3n), pfopen(3), de(4), ln(4), ni(4), qe(4), xna(4), ifconfig(8),
MAKEDEV(8), pfconfig(8c), pfstat(8)
.br
\fIThe Packet Filter: An Efficient Mechanism for User-Level Network
Code\fR
