!
!	CI BOOT COMMAND FILE - CIRA.CMD
!
! R1 MUST CONTAIN THE BI NODE NUMBER OF THE CI ADAPTER
! R2 MUST CONTAIN THE HSC # IN HEX
! R3 MUST CONTAIN THE DISK UNIT # IN HEX
! BEFORE INVOKING THIS PROCEDURE
!
D/G 0 20
D/G 4 0
D/G 5 1000B
D/G E 200
LOAD VMB.EXE/START:200
START 200
