.\" SCCSID: @(#)getwd.3	8.1	9/11/90
.TH getwd 3
.SH Name
getwd \- get current working directory pathname
.SH Syntax
.nf
.B char *getwd(pathname)
.B char *pathname;
.fi
.SH Description
.NXR "getwd subroutine"
.NXR "working directory" "getting pathname"
.NXA "directory" "working directory"
The
.PN getwd
subroutine 
copies the absolute pathname of the current working directory to
.I pathname
and returns a pointer to the result.
.SH Restrictions
The
.PN getwd
subroutine
may fail to return to the current directory if an error occurs.
.PP
Pathnames can be no longer than
MAXPATHLEN as defined in <sys/param.h>.
.SH Return Values
The
.PN getwd
subroutine
returns zero and places a message in
.I pathname
if an error occurs.
