.\" SCCSID: @(#)nlist.3	8.1	9/11/90
.TH nlist 3 VAX
.SH Name
nlist \- get entries from name list
.SH Syntax
.nf
.B #include <nlist.h>
.PP
.B nlist(filename, nl)
.B char *filename;
.B struct nlist nl[];
.fi
.SH Description
.NXR "nlist subroutine"
.NXR "name list" "defined"
.NXR "/vmunix file" "examining name list"
The
.PN nlist
subroutine
examines the name list in the given executable output file
and selectively extracts a list of values.
The name list consists of an array of structures containing names,
types and values.
The list is terminated with a null name.
Each name is looked up in the name list of the file.
If the name is found, the type and value of the
name are inserted in the next two fields.
If the name is not found, both entries are set to 0.
See 
.MS a.out 5
for the structure declaration.
.PP
This subroutine is useful
for examining the system name list kept in the file 
.PN /vmunix .
In this way programs can obtain system addresses that are up to date.
.SH Diagnostics
All type entries are set to 0 if the file cannot be found
or if it is not a valid name list.
.SH See Also
a.out(5)
