.\" SCCSID: @(#)pause.3	8.1	9/11/90
.TH pause 3
.SH Name
pause \- stop until signal
.SH Syntax
.B pause()
.SH Description
.NXR "pause subroutine" 
.NXA "kill system call" "pause subroutine"
.NXA "setitimer system call" "pause subroutine"
.NXR "process" "suspending"
The
.PN pause
subroutine never returns normally.
It is used to give up control while waiting for
a signal from 
.MS kill 2
or an interval timer, see 
.MS setitimer 2 .
Upon termination of a signal handler started during a
.PN pause ,
the
.PN pause
call will return.
.SH Diagnostics
The
.PN pause
subroutine always returns:
.TP 15
[EINTR]
The call was interrupted, that is,
always returns \-1.
.SH See Also
kill(2), select(2), sigpause(2)
