/*
 *  lpsmsg_string.h   Define LAPS error code --> message mapping
 *  
 *  Produced By: LpsmsgConvert/LpsmsgString utility 
 *
 *        Ajay Kachrani, Tue Nov  8 20:27:58 EST 1988
 *
 */
/*
 * bit mask for stripping VMS severity code from error codes
 */
#define SEVERITY_BITS 7
/*
 * severity codes
 * *NOTE* values must match ordering of severity strings
 */
#define SUCCESS	0
#define INFO	1
#define WARN	2
#define ERROR	3
#define	FATAL	4
/*
 * severity strings
 */
char *severity_strings[] =
{
     "", "", "warning: ", "error: ", "error: "
};

struct laps_msg {
        short severity;
	unsigned long code;
	short FAOcount;
	char *text;
};
int VMSmcount = 285;
struct laps_msg laps_msgs[] = {
/*
 * generic messages - used by various components of the print server
 */
SUCCESS, LPS$_NORMAL, 0, "Normal completion",
SUCCESS, LPS$_SUCCESS, 0, "Successful completion",
SUCCESS, LPS$_CONTINUE, 0, "Continue",
WARN, LPS$_STRTOOLON, 0, "String is too long - it has been truncated",
FATAL, LPS$_OSERROR, 1, "Operating System error detected - error was: %u",
FATAL, LPS$_PROBUNKNWN, 0, "Problem Unknown",
FATAL, LPS$_REBOOTREQD, 0, "Please reboot the PrintServer - FATAL ERROR",
SUCCESS, LPS$_PENDING, 0, "$QIO operation is pending",
SUCCESS, LPS$_USERDATA, 1, "userdata: %s",
INFO, LPS$_SYNC, 0, "Last Printer Job Complete, Ready for next job",
INFO, LPS$_JOBSTART, 1, "Job %u Start",
INFO, LPS$_JOBFINISH, 1, "Job %u Finish",
INFO, LPS$_JOBCONN, 1, "Job %u Connect",
INFO, LPS$_PROCSTART, 1, "Process %s Started",
INFO, LPS$_ABORTPEND, 1, "Pending Job %u Aborted",
INFO, LPS$_SENDTIMOUT, 0, "Timeout trying to send a message",
INFO, LPS$_PAUSE, 0, "Printer is paused (job is pending)",
INFO, LPS$_RESUME, 0, "Printer is resuming",
INFO, LPS$_CONNFAIL, 1, "Unable to connect to PrintServer %s ",
WARN, LPS$_BADPKTTYP, 0, "Invalid packet type",
WARN, LPS$_PAUSEABORT, 0, "Job aborted - Printer is still paused",
WARN, LPS$_ACCPTDISA, 0, "Job acceptance is disabled - job rejected",
ERROR, LPS$_SCINTERR, 0, "SC - Internal Error",
ERROR, LPS$_NOPRTCRT, 1, "Unable to create port %s in Status Collector",
ERROR, LPS$_NOPRCCRE, 1, "Unable to create process %s",
ERROR, LPS$_INVCONRES, 0, "Invalid PrintServer response to connect",
ERROR, LPS$_STNREJREQ, 0, "PrintServer rejected connect request",
ERROR, LPS$_LPSPCLERR, 0, "Job aborted due to PrintServer protocol error",
ERROR, LPS$_BADVERSION, 0, "Protocol version is not supported",
ERROR, LPS$_INVJOBTER, 0, "Invalid PrintServer to response to end-of-job",
ERROR, LPS$_JOBABORT, 1, "Job %u Aborted",
ERROR, LPS$_ABORTSRVMGT, 1, "Job %u Aborted by Server Management",
ERROR, LPS$_NOJOB, 0, "No Such Job",
ERROR, LPS$_IDENTTIMOUT, 0, "Controller ident message never received",
ERROR, LPS$_EVLLNKLST, 0, "Link lost to Supporting Host, disabling event logging",
FATAL, LPS$_PROCABORT, 1, "Process %s aborted",
FATAL, LPS$_LJCINTERR, 1, "Laps Init Process error, reason = %u",
FATAL, LPS$_LJCMONERR, 1, "Laps Monitor Process error, reason = %u",
FATAL, LPS$_LJCPROTERR, 1, "Laps Protocol Process error, reason = %u",
FATAL, LPS$_TRNFAIL, 1, "Translation from %s to PostScript failed.",
FATAL, LPS$_CANTUSETRN, 1, "Translator from %s to PostScript is unusable.",
WARN, LPS$_INVCTRBLK, 0, "Invalid Control Block received by controller",
WARN, LPS$_DISABLED, 0, "PrintServer is currently disabled and cannot accept jobs",
INFO, LPS$_JOBIDENT, 3, "Server Job=%u   Client Job=%u   User=%s",
WARN, LPS$_NOLOGNAM, 0, "cannot translate logical SYS$NODE (DECnet not running)",
FATAL, LPS$_PSSFTERR, 0, "Fatal PrintServer Software Error",
WARN, LPS$_UNCMPLTRNMH, 0, "Message handler Unable To Complete Transaction, Message May Be Lost",
WARN, LPS$_UNCMPLTRN, 0, "Status Process Unable To Complete Transaction, Message May Be Lost",
WARN, LPS$_UNCMPLQTRN, 0, "Query Process Unable to Complete Transaction, Response May Be Lost",
WARN, LPS$_UNKMSG, 0, "Invalid message received from PrintServer",
SUCCESS, LPS$_RESINPROG, 0, "Resource Fault in progress",
SUCCESS, LPS$_PSWDOK, 0, "Valid password presented to PrintServer",
SUCCESS, LPS$_RESAVAIL, 1, "Resource %s is available",
INFO, LPS$_RESFAULT, 1, "Resource Fault - %s resource needed",
INFO, LPS$_PSWDFAULT, 0, "Password Fault - password verification request",
INFO, LPS$_TRAYFAULT, 0, "Tray Fault - tray switch request",
WARN, LPS$_RESUNAVAIL, 1, "Resource %s Unavailable",
WARN, LPS$_RESCMPLTE, 1, "Resource %s Complete",
ERROR, LPS$_RESERR, 1, "Resource %s error",
ERROR, LPS$_RESNOSERV, 0, "No Resource Server is currently available",
ERROR, LPS$_RESABORT, 1, "Resource %s abort",
WARN, LPS$_PSWDNOTOK, 0, "Invalid password presented to PrintServer",
INFO, LPS$_SCSTART, 0, "Status Collector is started",
INFO, LPS$_LAPSSTART, 0, "LAPS Process started",
INFO, LPS$_FFMSTART, 0, "FFM Process started",
INFO, LPS$_SMSTART, 0, "Server Management started",
INFO, LPS$_MSHDLRSTART, 0, "Message Handler Process started",
INFO, LPS$_PRINTSTART, 0, "Printing Subsystem started",
ERROR, LPS$_KEYNOTREC, 1, "The keyword %s in the /PARAMETERS qualifier was not recognized",
ERROR, LPS$_PARSYNERR, 1, "Syntax error in the /PARAMETERS qualifier at or near %s ",
ERROR, LPS$_DEVSYNERR, 1, "Syntax error in /ON qualifier. %s not valid PrintServer name",
ERROR, LPS$_INVCONSOLE, 0, "Invalid Console Device",
ERROR, LPS$_TRNNOTFND, 1, "Translator from %s to PostScript not found ",
ERROR, LPS$_INTERINPROG, 1, "Interrupt already in progress - request denied",
ERROR, LPS$_PROTUNSUP, 1, "Function not supported in active LAPS protocol version",
ERROR, LPS$_NOLAYUPDIR, 0, "Layup definition area is not accessible",
ERROR, LPS$_NOLAYUPFIL, 1, "Layup definition module %s is not accessible",
INFO, LPS$_SHEETLIMOBS, 0, "Sheet_limit parameter is obsolete. Page_limit is being used instead",
INFO, LPS$_PRNAME, 1, "Message from PrintServer %s",
WARN, LPS$_LAYUPIGNORED, 0, "Layup_definition parameter ignored; since Number_up=0 was specified",
WARN, LPS$_NETRECOVER, 1, "Recoverable network error - print job %u requeued",
ERROR, LPS$_RESUBMIT, 1, "Unrecoverable checkpointed job %u in hold - please resubmit",
FATAL, LPS$_NETFAIL, 1, "Unrecoverable network error on job %u - queue restart required",
WARN, LPS$_CANTCHECKPNT, 1, "Checkpointed job %u is requeued",
WARN, LPS$_INTERRLOG, 0, "Event log Has Been Initialized",
WARN, LPS$_UNLMTEXC, 0, "Unprivileged connection limit exceeded - retrying...",
WARN, LPS$_SMRETRYCONN, 0, "PrintServer not responding to connect request - retrying...",
WARN, LPS$_NOCHANGE, 0, "Current and new passwords must be different - password not changed",
ERROR, LPS$_UNOPERRLOG, 1, "Unable to open Event Log file %s",
WARN, LPS$_CLSERRLOG, 0, "Event Log has been Disabled and Closed",
ERROR, LPS$_MNUNOTFND, 1, "Unable to open Menu Script file %s",
ERROR, LPS$_INVNODEID, 0, "Nodeid has improper form",
ERROR, LPS$_NOSUCHNODE, 0, "Node doesn't exist or isn't known to the Supporting Host",
ERROR, LPS$_NOSUCHPS, 0, "Node is not a PrintServer",
ERROR, LPS$_ENGNTRSPD, 0, "Print engine not responding to inquiry",
ERROR, LPS$_INSYNFAIL, 0, "Initialization/Synchronization failed",
ERROR, LPS$_CANTHAPPEN, 0, "Action should never happen",
ERROR, LPS$_INVCOMMAND, 0, "Invalid command",
ERROR, LPS$_INVCHAR, 0, "Invalid character entered",
ERROR, LPS$_INVCLASS, 0, "Invalid class",
ERROR, LPS$_INVPARM, 0, "Invalid parameter",
ERROR, LPS$_INVPASSWRD, 0, "Invalid password",
ERROR, LPS$_BADTIMVAL, 0, "Invalid time value",
ERROR, LPS$_NOROOM, 0, "No room to add anything more",
ERROR, LPS$_UNIMPL, 0, "Function is not implemented",
ERROR, LPS$_USERABORT, 0, "Action aborted by the user",
ERROR, LPS$_INVDATA, 0, "Invalid Data",
ERROR, LPS$_NOTFOUND, 0, "Entry not found",
ERROR, LPS$_OBJNOTFND, 0, "Object of the search was not found",
ERROR, LPS$_INVOBJTYP, 0, "Invalid Object Type",
ERROR, LPS$_INVOBJID, 0, "Invalid Object ID",
ERROR, LPS$_INVDATTYP, 0, "Invalid Data Type",
ERROR, LPS$_FAILED, 0, "Failed",
ERROR, LPS$_SMNOTRSPD, 0, "Connection failure - PrintServer not responding",
FATAL, LPS$_UNRECCDBFLD, 0, "Unrecognized CDB field - should never happen",
FATAL, LPS$_NOPRIV, 0, "No privilege for attempted operation",
FATAL, LPS$_NORSMJOB, 0, "No active Remote Server Management job on that PrintServer",
FATAL, LPS$_RSMBUG, 0, "Fatal bug in the Remote Server Management code",
WARN, LPS$_RONOCONN, 0, "Operator DISABLED - unable to make connection to Server",
ERROR, LPS$_PRVCONEXC, 0, "PrintServer privileged connection limit exceeded",
ERROR, LPS$_PSWDNOTVER, 0, "Password verification error - password not changed",
ERROR, LPS$_NOCDBAVL, 0, "No CDB file available - PrintServer configuration not changed",
ERROR, LPS$_CDBEOFFN, 0, "CDB has invalid format - PrintServer configuration not changed",
ERROR, LPS$_UNRCHABL, 0, "PrintServer node is currently unreachable",
ERROR, LPS$_NONETMBX, 0, "Remote Server Management requires NETMBX privilege",
ERROR, LPS$_UNDERLEN, 0, "The minimum required terminal page length is 24 lines",
ERROR, LPS$_NOACTJOB, 0, "No job currently active on PrintServer",
ERROR, LPS$_RSMDISC, 0, "Error occurred - connection to PrintServer lost",
ERROR, LPS$_DECNETOFF, 0, "DECnet is off - Server management requires DECnet be on",
ERROR, LPS$_RSMNETERR, 0, "Unexpected network error",
WARN, LPS$_ATOPMN, 0, "Attempting to open menu file",
WARN, LPS$_EVTLOGDISAB, 0, "Event logging disabled - event log not initialized",
FATAL, LPS$_LJCEXPERR, 1, "Laps-Interrupt Process error, reason = %s",
ERROR, LPS$_INVFEAT, 0, "This feature is not available on this model printer.",
INFO, LPS$_IDLE, 0, "Idle",
INFO, LPS$_ACTIVE, 0, "Active",
WARN, LPS$_EXITSRVR, 0, "exitserver has been executed - permanent state may be changed",
ERROR, LPS$_FLUSHING, 0, "Rest of Job (to EOJ) will be ignored",
WARN, LPS$_DICTFULL, 1, "dictfull: No more room in dictionary - offending command is %s",
WARN, LPS$_DICTSTKOV, 0, "dictstackoverflow: Too many begins",
WARN, LPS$_DICTSTKUF, 0, "dictstackunderflow: Too many ends",
WARN, LPS$_EXECSTKOV, 1, "execstackoverflow: exec nesting is too deep - offending command is %s",
WARN, LPS$_INTERUPT, 0, "interrupt: The job has been interrupted",
WARN, LPS$_INVACC, 1, "invalidaccess: Attempt to access restricted object or capability - offending command is %s",
WARN, LPS$_INVEXIT, 0, "invalidexit: exit not in loop",
WARN, LPS$_INVFILACC, 1, "invalidfileaccess: Bad file access string - offending command is %s",
WARN, LPS$_INVFONT, 1, "invalidfont: Bad font name or dictionary - offending command is %s",
WARN, LPS$_INVREST, 1, "invalidrestore: Improper restore - offending command is %s",
WARN, LPS$_IOERROR, 1, "ioerror: System I/O error occurred - offending command is %s",
WARN, LPS$_LIMCHK, 1, "limitcheck: Implementation limit exceeded - offending command is %s",
WARN, LPS$_NOCURPT, 1, "nocurrentpoint: Path is empty - offending command is %s",
WARN, LPS$_RANGECHK, 1, "rangecheck: Argument out of bounds - offending command is %s",
WARN, LPS$_STKOFLO, 1, "stackoverflow: Operand stack overflow - offending command is %s",
WARN, LPS$_STKUFLO, 1, "stackunderflow: Operand stack underflow - offending command is %s",
WARN, LPS$_SYNERR, 1, "syntaxerror: Input ended in string or procedure body - offending command is %s",
WARN, LPS$_TIMOUT, 0, "timeout: Time limit exceeded",
WARN, LPS$_TYPCHK, 1, "typecheck: Argument of wrong type - offending command is %s",
WARN, LPS$_UNDEF, 1, "undefined: Name not known - offending command is %s",
WARN, LPS$_UNDFILNAM, 1, "undefinedfilename: File not found - offending command is %s",
WARN, LPS$_UNDEFRES, 1, "undefinedresult: Number overflow or underflow - offending command is %s",
WARN, LPS$_UNMATCH, 1, "unmatchedmark: Expected mark not on stack - offending command is %s",
WARN, LPS$_UNREGIST, 1, "unregistered: PostScript has encountered a system error - offending command is %s",
WARN, LPS$_VMERROR, 1, "VMerror: PostScript virtual memory exhausted - offending command is %s",
WARN, LPS$_CFGERROR, 2, "configurationerror: %s - offending command is %s",
WARN, LPS$_PSINCONSIST, 0, "PostScript controller state is inconsistent",
WARN, LPS$_PSQUITOPER, 0, "PostScript quit operator has been executed",
WARN, LPS$_PSFATALSYS, 1, "PostScript fatal error at PC %u",
INFO, LPS$_TRAYSFULL, 0, "Upper and lower output trays full",
INFO, LPS$_DLVLOWER, 0, "Output being delivered to lower tray",
INFO, LPS$_DLVUPPER, 0, "Output being delivered to upper tray",
INFO, LPS$_SWTCHUPPER, 0, "Lower output tray full, switching to upper",
INFO, LPS$_SWTCHLOWER, 0, "Upper output tray full, switching to lower",
SUCCESS, LPS$_PRNTREDY, 0, "Print Engine ready",
SUCCESS, LPS$_PRNTERRCORR, 0, "Print Engine error has been corrected",
INFO, LPS$_MAINT50K, 0, "Print Engine 50,000 page maintenance required",
INFO, LPS$_MAINT100K, 0, "Print Engine 100,000 page maintenance required",
INFO, LPS$_MAINT200K, 0, "Print Engine 200,000 page maintenance required",
INFO, LPS$_OILLOW, 0, "Print Engine oil supply low",
INFO, LPS$_TNRLOW, 0, "Print Engine toner supply low",
INFO, LPS$_WARMUP, 0, "Print Engine is in warmup state",
WARN, LPS$_EJECTJAM, 0, "Print Engine paper eject section is jammed",
WARN, LPS$_TRANSJAM, 0, "Print Engine transport section is jammed",
WARN, LPS$_UPTRAYJAM, 0, "Print Engine upper paper tray is jammed",
WARN, LPS$_LOTRAYJAM, 0, "Print Engine lower paper tray is jammed",
WARN, LPS$_LCITJAM, 0, "Print Engine large capacity paper tray is jammed",
WARN, LPS$_UPTRAYEMP, 0, "Print Engine upper paper tray is empty",
WARN, LPS$_LOTRAYEMP, 0, "Print Engine lower paper tray is empty",
WARN, LPS$_LCITEMP, 0, "Print Engine large capacity paper tray is empty",
WARN, LPS$_COVOPN, 0, "Print Engine cover is open",
WARN, LPS$_TNRMALADJ, 0, "Print Engine toner cartridge setting is incorrect",
WARN, LPS$_TRNMALADJ, 0, "Print Engine transport path setting is incorrect",
WARN, LPS$_FUSMALADJ, 0, "Print Engine fusing unit setting is incorrect",
WARN, LPS$_FDSTAKJAM, 0, "Face down stacker is jammed",
WARN, LPS$_FDSTAKFULL, 0, "Face down stacker is full",
WARN, LPS$_FDSTAKOPEN, 0, "Face down stacker cover is open",
WARN, LPS$_LCSTAKJAM, 0, "Large capacity stacker is jammed",
WARN, LPS$_LCSTAKFULL, 0, "Large capacity stacker is full",
WARN, LPS$_LCSTAKOPEN, 0, "Large capacity stacker cover is open",
WARN, LPS$_RESERVED1, 0, "BAD MESSAGE",
WARN, LPS$_RESERVED2, 0, "BAD MESSAGE",
WARN, LPS$_RESERVED3, 0, "BAD MESSAGE",
WARN, LPS$_RESERVED4, 0, "BAD MESSAGE",
WARN, LPS$_RESERVED5, 0, "BAD MESSAGE",
WARN, LPS$_RESERVED6, 0, "BAD MESSAGE",
WARN, LPS$_OFFLINE, 0, "Print Engine has gone off line",
WARN, LPS$_PRNOTRDY, 0, "Print Engine is not ready",
WARN, LPS$_TNREND, 0, "Print Engine toner supply is exhausted",
WARN, LPS$_LCITCOVOPEN, 0, "Large capacity tray cover is open",
ERROR, LPS$_PRHDWERR, 1, "Print Engine hardware error: %s",
ERROR, LPS$_PRUNKERR, 2, "Print Engine unknown error status: %u, %u",
FATAL, LPS$_POWERERR, 0, "Print Engine power supply unit error - FATAL ERROR",
FATAL, LPS$_DRIVEERR, 0, "Print Engine driving unit error - FATAL ERROR",
FATAL, LPS$_FUSINGERR, 0, "Print Engine fusing error - FATAL ERROR",
FATAL, LPS$_FEEDERR, 0, "Print Engine paper feed unit error - FATAL ERROR",
FATAL, LPS$_OPTICERR, 0, "Print Engine optical unit error - FATAL ERROR",
FATAL, LPS$_FDSTAKERR, 0, "Face down stacker unit error - FATAL ERROR",
FATAL, LPS$_LCSTAKERR, 0, "Large capacity stacker unit error - FATAL ERROR",
FATAL, LPS$_MBSTAKERR, 0, "Mailbox stacker unit error - FATAL ERROR",
FATAL, LPS$_DUPSTAKERR, 0, "Duplexer unit error - FATAL ERROR",
WARN, LPS$_PRSERVICE, 2, "Printer requires service: code = %u %u",
INFO, LPS$_MAINT20K, 0, "Print Engine 20,000 page maintenance required",
INFO, LPS$_MAINT80K, 0, "Print Engine 80,000 page maintenance required",
INFO, LPS$_MAINT300K, 0, "Print Engine 300,000 page maintenance required",
INFO, LPS$_ONLINE, 0, "Print Engine has gone online",
WARN, LPS$_DUPJAM, 0, "Duplexer unit is jammed",
WARN, LPS$_DUPOPEN, 0, "Duplexer cover is open",
WARN, LPS$_DUPUNSEAT, 0, "Duplexer paper path is not properly seated",
WARN, LPS$_FUSERUNSEAT, 0, "Fuser unit absent or improperly seated",
WARN, LPS$_CLEANUNSEAT, 0, "Cleaning unit absent or improperly seated",
WARN, LPS$_OPCUNSEAT, 0, "OPC drum absent or improperly seated",
WARN, LPS$_DEVUNSEAT, 0, "Developer unit absent or improperly seated",
WARN, LPS$_OUTCOVOPEN, 0, "Paper output cover is open",
WARN, LPS$_SIDECOVOPEN, 0, "Print engine side cover is open",
WARN, LPS$_UPTRAYOUT, 0, "Upper paper tray is missing or misaligned",
WARN, LPS$_LOTRAYOUT, 0, "Lower paper tray is missing or misaligned",
WARN, LPS$_LCSSHELFOUT, 0, "LCOS paper shelf is missing or misaligned",
WARN, LPS$_SIDEFULL, 0, "Side output tray full",
WARN, LPS$_UPFULL, 0, "Upper LCOT full",
WARN, LPS$_LOFULL, 0, "Lower LCOT full",
WARN, LPS$_ADJTRAY, 0, "Side tray not correctly positioned",
WARN, LPS$_NOTRAY, 0, "Unavailable paper destination selected",
WARN, LPS$_CLEANFULL, 0, "Cleaning unit full - needs replacement",
WARN, LPS$_REPLDRUM, 0, "OPC drum needs replacement",
WARN, LPS$_DENSADJUST, 0, "Image density adjustment required",
WARN, LPS$_UPWRONGMEDIA, 0, "Incorrect media in upper paper tray",
WARN, LPS$_LOWRONGMEDIA, 0, "Incorrect media in lower paper tray",
WARN, LPS$_LCWRONGMEDIA, 0, "Incorrect media in LCIT",
WARN, LPS$_WRONGMEDIA, 0, "Media incompatible with duplexer or output device",
WARN, LPS$_LCOTSMALL, 0, "Media too small for LCOS - going to top output tray",
WARN, LPS$_LCOTDIFF, 0, "Media differs from LCOS setting - going to top tray",
WARN, LPS$_DPXXJAM, 0, "Please clear paper jam caused by DPX transport station",
WARN, LPS$_DPXFJAM, 0, "Please clear paper jam caused by DPX feed path",
WARN, LPS$_FUSJAM, 0, "Please clear paper jam caused by fusing unit",
WARN, LPS$_LOXJAM, 0, "Please clear paper jam caused by lower transport station",
WARN, LPS$_UPXJAM, 0, "Please clear paper jam caused by upper transport station",
WARN, LPS$_MAINXJAM, 0, "Please clear paper jam caused by main transport station",
FATAL, LPS$_FSCALL, 0, "Call Field Service to correct error",
WARN, LPS$_TABJAM, 0, "Please clear paper jam caused by table unit",
WARN, LPS$_ERRJAM, 0, "Please clear paper jam caused by fatal engine error",
WARN, LPS$_COVJAM, 0, "Please clear paper jam caused by opened cover",
ERROR, LPS$_COMMOFLOW, 0, "Engine command buffer overflow -- reboot PrintServer",
ERROR, LPS$_COMMLOST, 0, "Communication with print engine lost -- reboot PrintServer",
WARN, LPS$_LOSTPATH, 0, "The current path may have been lost.",
WARN, LPS$_NOCOPYPG, 0, "'copypage' is not supported by multi-page layup.",
ERROR, LPS$_ZEROAREA, 0, "Layup definition margins result in no usable sheet area.",
ERROR, LPS$_NEGAREA, 0, "Layup definition margins overlap one another.",
WARN, LPS$_PPSGTNUP, 0, "Pages per sheet are greater than number up.  Pages per sheet set to number up.",
WARN, LPS$_FPGGTPPS, 0, "First page is greater than pages per sheet.  First page set to 1.",
WARN, LPS$_NOSETTRAY, 0, "Tray selection is not supported by multi-page layup.",
ERROR, LPS$_SIZNOTAVL, 2, "No %s size medium is loaded in %s.",
ERROR, LPS$_SIZNOTSUP, 2, "%s size medium is not supported by %s.",
ERROR, LPS$_SIZNOTRAY, 3, "%s size medium in not in the %s tray in %s.",
FATAL, LPS$_FTLDEVCTL, 2, "Fatal device control library problem.  Config error:  %s on %s",
INFO, LPS$_UPPRPGLIM, 0, "The upper page limit has been reached.  Remaining pages will be flushed.",
INFO, LPS$_TRAYSUBST, 2, "Output will be delivered to the %s tray on %s.",
ERROR, LPS$_TRYNOTRDY, 3, "%s tray on %s is %s.",
ERROR, LPS$_DPLXNOSUP, 1, "%s does not support duplex printing.",
ERROR, LPS$_TUMBNOSUP, 1, "%s does not support tumble printing.",
ERROR, LPS$_NOINPTRAY, 1, "Input tray selection not supported for %s.",
ERROR, LPS$_NOOUTTRAY, 2, "Output tray, '%s', not supported on %s.",
WARN, LPS$_BADLAYDEF, 2, "%s on line %s in layup definition.",
INFO, LPS$_PROLOGIS, 2, "Prologue %s, version %s",
INFO, LPS$_BADPASSWD, 0, "Bad password",
ERROR, LPS$_NODUPFACEUP, 1, "Duplex to 'face_up' output tray is not supported on %s",
ERROR, LPS$_NOONESDUP, 1, "One_sided_duplex is not supported on %s",
0, 0, 0, (char *) 0
};
