.TH rain 6 "" "" Unsupported
.SH Name
rain \- animated raindrops display
.SH Syntax
/usr/games/rain
.SH Description
.NXR "rain display"
.PP
The
.PN rain
program's
display is modeled after the VAX/VMS program of the same name.
The terminal has to be set for 9600 baud to obtain the proper effect.
.PP
As with all programs that use
.IR termcap ,
the TERM environment
variable must be set (and exported) to the type of the terminal being used.
.SH Files
.PN /etc/termcap
