.\" SCCSID: @(#)users.1	8.1	9/11/90
.\" Last modified by MJT on 26-Aug-85  2324
.\"  Repaired beginning matter to work right in whatis database
.TH users 1
.SH Name
users \- print names of users who are logged in
.SH Syntax
.B users
.SH Description
.NXR "users command"
.NXA "users command" "who command"
.NXA "users command" "finger command"
.NXR "system" "showing users"
The
.PN users
command
lists the login names of the users currently on the system in a compact,
one-line format.
.SH Files
/etc/utmp
.SH See Also
who(1)
