.\" SCCSID: @(#)end.3	8.1	9/11/90
.TH end 3 RISC
.SH Name
end, etext, edata \- last locations in program
.SH Syntax
.nf
.B extern end;
.B extern etext;  
.B extern edata;  
.B extern eprol;
.fi
.SH Description
.NXR "end subroutine"
.NXR "etext subroutine"
.NXR "edata subroutine"
.NXR "program" "specifying addresses"
These names refer neither to routines nor to locations with interesting
contents.  The address of
.PN etext
is the first address above the program text,
.PN edata
above the initialized data region, and
.PN eprol
is the first instruction of the user's program that follows the
runtime startup routine.
.PP
When execution begins, the program break coincides with 
.PN end ,
but it is reset by the routines
.MS brk 2 ,
.MS malloc 3 ,
standard input/output
.MS stdio 3s ,
the profile
.RB ( \-p )
option of 
.MS cc 1 ,
and so forth.
The current value of the program break
is reliably returned by sbrk(0).
For further information, see 
.MS brk 2 .
.SH See Also
cc(1), brk(2), malloc(3), stdio(3s)
