.\" SCCSID: @(#)sigpause.2	8.1	9/11/90
.TH sigpause 2
.SH Name
sigpause \- atomically release blocked signals and wait for interrupt
.SH Syntax
.ft B
sigpause(sigmask)
.br
int sigmask;
.ft R
.SH Description
.NXR "sigpause system call"
.NXA "sigblock system call" "sigpause system call"
.NXR "signal" "releasing blocked"
The
.PN sigpause
system call
assigns 
.I sigmask
to the set of masked signals
and then waits for a signal to arrive.
On return, the set of masked signals is restored.
The
.I sigmask
is usually 0 to indicate that no
signals are now to be blocked.
The
.PN sigpause
always terminates by being interrupted, returning EINTR.
.PP
In normal usage, a signal is blocked using
.MS sigblock 2 
at the beginning of a critical section of code.
Variables modified on the occurrence
of the signal are examined to determine if there is any work
to be done. The process pauses, awaiting work, by using
.PN sigpause
with the mask returned by
.PN sigblock .
.SH See Also
sigblock(2), sigvec(2)
