.TH capsar 1
.SH Name
capsar \- prepares documents not in ASCII format for transport in the mail system
.SH Syntax
.B capsar 
[-c] 
[-t] 
[-x[hTD]] 
[\fIfile\fP]
.SH Description
.NXR "capsar utility"
The 
.PN capsar
utility allows ULTRIX mail to support documents containing
non-ASCII data, such as DDIF.
Only the DDIF and DOTS data types are currently supported.
DDIF is Digital's standard format for document 
interchange. DOTS is an encapsulation of the encoded 
interchange form of a number
of related data objects into a single composite object.
For more information, see
.MS DDIF 5 
and 
.MS DOTS 5 .
.PP
The 
.PN capsar 
utility prepares a DOTS file or a DDIF document for transport in the mail
system by performing the following steps: 
.TP 6
1)
The DDIF document is converted to DOTS format.  As a DDIF 
document may contain more than one file, all files within the DDIF 
document are incorporated into one DOTS file which can be sent 
as one mail message.
.TP
2)
Each DOTS file is then compressed and encoded
using only printing ASCII characters.   This is because 
ULTRIX mail software only supports 7 bit mail.
.TP
3)
The 
.PN capsar
routine encapsulates coded documents 
by adding leading and trailing lines, each
surrounded by a <CR>.  The lines should begin with 2 or more dashes
(\-) and some text that indicates the
nature of the encapsulated message. The following is a typical encapsulated
mail message:
.EX
To: anybody@anynode
Cc:
Subject: Another DDIF document

	
-----------motd.ddif : DOTS.ctod.compress.uuencode message 

begin 0 motd.ddif
M__]\@*" ,(" !BO.#P$# 8$* &UO=&0N9&1I9H0$)%546     "A@"B !@8K
MS@\! P$''T1$248M96YC;V1E9"!R979I<V%B;&4@9&]C=6UE;G2@@/__?X"@
M@( ! 8$! ((/1$1)1B1?4D5!1%]415A4HX#)% !$1$E&(%1E>'0@1G)O;G0@
 
end

-----------End of motd.ddif : DOTS.ctod.compress.uuencode message 
.EE
The
.PN capsar 
command can also extract different parts of a mail message,
namely, the header information, the text part of the message,
and the DOTS file that was encapsulated as described above.
.PP
Extracting the DOTS file is done by
parsing the mail message and detecting the leading and trailing
encapsulation boundaries.  Decoding and uncompressing the data  
results in the original DOTS file.
.PP
The 
.PN capsar 
utility is built into Rand MH to provide DDIF mail 
support.  It can, however, be used with 
.PN ucb 
mail.
.SH Options
.TP 5
.B \-c
Causes 
.PN capsar 
to create an encapsulated DOTS bodypart
from \fIfile\fP. The \fIfile\fP must be a DOTS/DDIF type document.
.TP
.B \-t
Causes 
.PN capsar
to write to the standard output the message type of
\fIfile\fP. Message type can be either text or DOTS.
.TP
.B \-xh
Extracts the mail header lines from \fIfile\fP. 
The header line
must be at the beginning of the \fIfile\fP and 
separated from the remaining
text by a <CR> or <CRLF>.  Each header line is a string containing
a header field name (for example, Subject), 
a colon (:), one or more spaces,
and a field value.  Each header line may have embedded continuation
sequences it it (for example, LF followed by spaces or tabs).
.TP
.B \-xT
Extracts all the text parts of the mail message 
in \fIfile\fP
to the standard output.
.TP
.B \-xD
Extracts any DOTS bodyparts in \fIfile\fP. The DOTS
document is sent to the standard output.
This is the reverse of the \fB\-c\fP option above.
.IP
The \fIfile\fP must be specified for the \fB\-c\fP option. 
If \fIfile\fP is not specified
with the \fB\-x\fP or \fB\-t\fP option then the standard input is used.
.SH Examples
.PP
The following are examples of how to use the 
.PN capsar
command:
.PP
Encapsulates a DDIF document
.EX 
capsar \-c file.ddif | more     
.EE
.PP
Lists the header line from the mail message
.EX
capsar \-xh file.mail    
.EE
.PP
Extracts the encapsulated DOTS file from the file
.EX
capsar \-xD file > file.dots

	or

capsar \-xD file | dtoc
.EE
.PP
In order to mail a DDIF/DOTS document you can use one of the following:
.EX 
capsar \\-c file.ddif | mail \-s "subject" address

capsar \-c file.ddif | mhmail \-subject "subject" address
.EE
.PP 
Use the second command if you are using RAND mh.
.PP
A DOTS file is extracted from dxmail first extracting the 
message into a file. The dxmail utility has an extract feature 
built in so
.PN "capsar \-xD"
isn't needed.
.SH See Also
compress(1), ctod(1), dtoc(1), mail(1), mh(1mh),
mhmail(1mh), uuencode(1), vdoc(1), prompter(1mh), 
DDIF(5), DOTS(5)
