.\" SCCSID: @(#)cb.1	8.1	9/11/90
.\" SCCSID: @(#)cb.1	8.1	9/11/90
.TH cb 1
.SH Name
cb \- C program beautifier
.SH Syntax
.B cb
.SH Description
.NXR "cb program"
.NXR "C program" "displaying on standard output"
The
.PN cb
command places a copy of the C program from the standard input
on the standard output with spacing and indentation
that displays the structure of the program.
