.\" SCCSID: @(#)help.1	8.2	10/29/90
.TH help 1
.SH Name
help \- tips on getting started with an ULTRIX system
.SH Syntax
.B help
.SH Description
The 
.PN help
command displays information
on how to get started using an ULTRIX operating system.  It 
recommends
places to start with the ULTRIX documentation, and
gives a list of commands helpful to beginners.
