.\" SCCSID: @(#)rev.1	8.1	9/11/90
.TH rev 1 
.SH Name
rev \- reverse character positions in file data
.SH Syntax
.B rev
[\|\fIfile...\fR\|]
.SH Description
.NXR "rev command"
.NXR "file" "reversing lines"
The
.PN rev
command copies the named files to the standard output,
reversing the order of characters in every line.
If no file is specified, the standard input is copied.
